# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wxzq4T2S6ZAr1Abxr9coZ5OVyooTJSel
"""

import datetime
import os
import base64
from io import BytesIO
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd

def main():

    tickers = ['AAPL', 'GOOG']
    data = yf.download(tickers, period='2d', group_by='ticker')

    results = []

    for ticker in tickers:
        ticker_data = data[ticker]

        if len(ticker_data) >= 2:
            close_yesterday = ticker_data['Close'].iloc[-2]
            close_today = ticker_data['Close'].iloc[-1]
            pct_change = ((close_today - close_yesterday) / close_yesterday) * 100
        else:
            close_today = ticker_data['Close'].iloc[-1]
            open_today = ticker_data['Open'].iloc[-1]
            pct_change = ((close_today - open_today) / open_today) * 100

        results.append({
            'Ticker': ticker,
            'Zmena_Pct': round(pct_change, 2),
            'Cena_USD': round(close_today, 2)
        })

    df_results = pd.DataFrame(results)
    print("Výsledky analýzy:")
    print(df_results)


    winner = df_results.loc[df_results['Zmena_Pct'].idxmax()]
    winner_text = f"Dnes více rostla (nebo méně klesala) akcie <strong>{winner['Ticker']}</strong> se změnou <strong>{winner['Zmena_Pct']}%</strong>."


    # Generování Bar Chartu do paměti (Base64)
    # Tímto trikem nemusíme ukládat obrázek zvlášť, ale vložíme ho přímo do HTML kódování.
    plt.figure(figsize=(6, 4))
    colors = ['#1f77b4' if x >= 0 else '#d62728' for x in df_results['Zmena_Pct']]
    bars = plt.bar(df_results['Ticker'], df_results['Zmena_Pct'], color=colors, edgecolor='black', width=0.5)

    plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
    plt.ylabel('Denní změna (%)')
    plt.title('Porovnání dnešního výkonu: AAPL vs GOOG')


    for bar in bars:
        yval = bar.get_height()
        va_dir = 'bottom' if yval >= 0 else 'top'
        plt.text(bar.get_x() + bar.get_width()/2.0, yval, f"{yval}%", ha='center', va=va_dir, fontweight='bold')

    plt.tight_layout()

    # Uložení grafu do stringu (Base64 encodování)
    buf = BytesIO()
    plt.savefig(buf, format='png', dpi=150)
    plt.close()
    buf.seek(0)
    image_base64 = base64.b64encode(buf.read()).decode('utf-8')


    # Sestavení finálního HTML reportu
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    html_content = f"""<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analýza US Stock Market</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f4f7f6; color: #333; }}
        .container {{ max-width: 700px; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin: 0 auto; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; }}
        .meta {{ color: #7f8c8d; font-size: 0.9em; margin-bottom: 20px; }}
        .result-box {{ background-color: #e8f8f5; border-left: 5px solid #2ecc71; padding: 15px; margin: 20px 0; border-radius: 4px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f8f9fa; }}
        .graph-container {{ text-align: center; margin-top: 30px; }}
        img {{ max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 4px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Denní analýza: AAPL vs GOOG</h1>
        <div class="meta">Poslední aktualizace: {now_str}</div>

        <div class="result-box">
            {winner_text}
        </div>

        <h2>Tabulka hodnot</h2>
        <table>
            <tr>
                <th>Ticker</th>
                <th>Aktuální Cena (USD)</th>
                <th>Denní Změna (%)</th>
            </tr>
            <tr>
                <td>{df_results.iloc[0]['Ticker']}</td>
                <td>${df_results.iloc[0]['Cena_USD']}</td>
                <td>{df_results.iloc[0]['Zmena_Pct']}%</td>
            </tr>
            <tr>
                <td>{df_results.iloc[1]['Ticker']}</td>
                <td>${df_results.iloc[1]['Cena_USD']}</td>
                <td>{df_results.iloc[1]['Zmena_Pct']}%</td>
            </tr>
        </table>

        <div class="graph-container">
            <h2>Vizualizace výkonu</h2>
            <img src="data:image/png;base64,{image_base64}" alt="Porovnání akcií">
        </div>
    </div>
</body>
</html>
"""

    # Zápis do souboru index.html
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)

    print("Analýza dokončena. Soubor index.html byl úspěšně vygenerován.")


if __name__ == "__main__":
    main()